name: meuh_life #TODO Change the name of the app, Add icon launch (especially iOS)
description: Meuh Life App
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.7
  cached_network_image: ^2.2.0 # only mobile
  image_cropper: ^1.2.1 # only mobile
  flutter_speed_dial: ^1.2.5
  provider: ^4.1.2
  photo_view: ^0.9.2
  bubble: ^1.1.9+1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2 # only mobile
  timeago: ^2.0.26
  like_button: ^0.2.0
  image_picker: ^0.6.6+1 # TODO: Add image picker to iOS  # only mobile
  firebase_auth: ^0.14.0+5 # TODO Add firebase to iOS config
  firebase_database: ^3.0.7
  firebase_storage: ^3.1.5
  firebase_image: ^0.1.5
  cloud_firestore: ^0.13.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: Marker
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf

